FROM mcr.microsoft.com/mssql/server:2019-latest
ENV ACCEPT_EULA y
ENV SA_PASSWORD MasteryDevelopment1
COPY ./mssql.init.sql .
COPY ./mssql.entrypoint.sh .
EXPOSE 1433
CMD /bin/bash ./mssql.entrypoint.sh